### ISSUE TITLE
Does not build on arm64

### ISSUE THREAD

**Issue by jdidion** [milkschen/leviosam2#3]
The issue is in your cmake file. You do `STRING(FIND ${CPUINFO} "sse4_1" SSE4_1_TRUE)` which sets `SSE4_1_TRUE=-1` when "sse4_1" is not found. Then you do `IF (SSE4_1_TRUE)` and since `-1` is a non-zero number it evaluates to true.

**Comment by jdidion** [comment]
Looks like it works if you change the if statement to `IF (SSE2_TRUE GREATER 0)`

**Comment by jdidion** [comment]
After fixing that I am now getting a linker error:

```
#0 61.06 [100%] Linking CXX executable leviosam2
#0 61.12 /usr/bin/ld: liblvsam.a(aln.cpp.o): in function `Aln::align_ksw2(char const*, char const*, Aln::AlnOpts const&, std::vector<unsigned int, std::allocator<unsigned int> >&, int&)':
#0 61.12 aln.cpp:(.text+0x28d0): undefined reference to `ksw_extd2_sse'
#0 61.12 /usr/bin/ld: aln.cpp:(.text+0x29d0): undefined reference to `ksw_extz2_sse'
```

**Comment by jdidion** [comment]
If you don't have access to an M1 mac I'm happy to test out a PR

**Comment by milkschen** [comment]
I don't have an M1 Mac. I just pushed the cmake changes to branch `arm64`, which compiled for me on linux x86_64 and mac x86_64. It'd be great if you can test a PR.

**Comment by jdidion** [comment]
That resolves the cmake issue but it still fails on the linker issue. I am guessing there needs to be a conditional depending on whether sse instructions are available to determine whether to use the sse or non-see versions of ksw fuctions.

**Comment by milkschen** [comment]
We will explore non-SSE solutions to complement the ksw2 module when we have bandwidth. We expect Rosetta emulation to be a tentative solution on Mac M1.

**Comment by ch4rr0** [comment]
Hello,

I create a PR for this which have tested on an ARM SBC. It would help getting this PR approved if you can test whether it works on Apple M1, too.

**Comment by milkschen** [comment]
This is addressed in #43 (thanks to @ch4rr0) and #45. I'm interested in supporting an image based on arm64 in the future.
